### ISSUE TITLE
Can't upload image to web frontend

### ISSUE THREAD

**Issue by renzyndrome** [Merctrans/docker-odoo-production#1]
How to replicate:
Upload any image in designing the website
or
in the backend, go to settings -> update company -> upload logo

error 1:
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)

error 2:
web#id=1&cids=1&menu…ny&view_type=form:1 Uncaught SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous>

![image](https://user-images.githubusercontent.com/39470762/205467475-3c99715b-29cb-424c-95ec-ec2920c11689.png)

**Comment by renzyndrome** [comment]
i also tried to set max upload to nginx config

`# increase upload max
    client_max_body_size 64M;`

**Comment by hglong16** [comment]
Thank for report, please try new odoo version https://github.com/Merctrans/docker-odoo-production/releases/tag/16.0
